//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSOCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventType
    {
        public string Type { get; set; }
        public Nullable<bool> InPentamind { get; set; }
        public Nullable<bool> Display { get; set; }
        public string Extention { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
