//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSOCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_Resource
    {
        public int INDEX { get; set; }
        public string Event_Code { get; set; }
        public string Resource { get; set; }
        public Nullable<int> QTY { get; set; }
        public Nullable<int> Per { get; set; }
    }
}
