//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSOCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameVariant
    {
        public GameVariant()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int GameId { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual ICollection<Event> Events { get; set; }
    }
}
