//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSOCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameCategory
    {
        public GameCategory()
        {
            this.Games = new HashSet<Game>();
        }
    
        public int Id { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<Game> Games { get; set; }
    }
}
