//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSOCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Information
    {
        public Nullable<int> Mind_Sport_ID { get; set; }
        public string Info { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<bool> AllYears { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
