//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSOOrganiser
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medal_Point
    {
        public Nullable<float> Order { get; set; }
        public string Colour { get; set; }
        public Nullable<int> Points { get; set; }
        public byte[] Picture { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
