//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSOCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class National_Flag
    {
        public string Nationality { get; set; }
        public byte[] Flag { get; set; }
        public string Continent { get; set; }
        public string Code { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
