//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSOCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Olympiad_Info
    {
        public Olympiad_Info()
        {
            this.Events = new HashSet<Event>();
            this.Locations = new HashSet<Location>();
            this.WomenNotInWomensPentaminds = new HashSet<WomenNotInWomensPentamind>();
            this.MetaGameDefinitions = new HashSet<MetaGameDefinition>();
        }
    
        public Nullable<int> YearOf { get; set; }
        public string Number { get; set; }
        public string Title { get; set; }
        public string Venue { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public Nullable<decimal> MaxFee { get; set; }
        public Nullable<decimal> MaxCon { get; set; }
        public Nullable<System.DateTime> AgeDate { get; set; }
        public Nullable<int> JnrAge { get; set; }
        public Nullable<int> SnrAge { get; set; }
        public Nullable<int> PentaLong { get; set; }
        public Nullable<int> PentaTotal { get; set; }
        public bool Current { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public int Id { get; set; }

        public string Ruleset { get; set; }

        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<WomenNotInWomensPentamind> WomenNotInWomensPentaminds { get; set; }
        public virtual ICollection<MetaGameDefinition> MetaGameDefinitions { get; set; }
    }
}
