//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSOCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paring
    {
        public int INDEX { get; set; }
        public string Event_Code { get; set; }
        public Nullable<int> Round { get; set; }
        public Nullable<int> Board { get; set; }
        public Nullable<int> White { get; set; }
        public Nullable<float> WScore { get; set; }
        public Nullable<int> Black { get; set; }
        public Nullable<float> BScore { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
