//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSOOrganiser
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentNumber { get; set; }
        public Nullable<int> MindSportsID { get; set; }
        public Nullable<decimal> Payment1 { get; set; }
        public string Payment_Method { get; set; }
        public Nullable<int> Banked { get; set; }
        public string Card_name { get; set; }
        public string Expiry_date { get; set; }
        public string Issue { get; set; }
        public string Card_number { get; set; }
        public string Card_Address_1 { get; set; }
        public string Card_Address_2 { get; set; }
        public string Card_City { get; set; }
        public string Card_County { get; set; }
        public string Card_Post_code { get; set; }
        public string Card_Country { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual Contestant Name { get; set; }
    }
}
