//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSOCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelectedPeople
    {
        public Nullable<int> MSOID { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<bool> Printed { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
