//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSOOrganiser
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public string Resource1 { get; set; }
        public Nullable<int> MSO_Stock { get; set; }
        public string Source { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> Per { get; set; }
        public int INDEX { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
