//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSOOrganiser
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelectedCategory
    {
        public int ID { get; set; }
        public string Category { get; set; }
        public Nullable<bool> Current { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
